POST http://localhost:3000/createStakes HTTP/1.1
Content-Type: application/json

{
    "requestId" : "ae41f5ca-3dbb-4e03-93f1-50e6197215fe",
    "deposits" : [
        {
            "depositId": 1,
            "user" : "BadAddress",
            "amount" : 100,
            "yieldConfigId" : 1,
            "depositTime" : 1664996203
        }
    ]
}